[package]
name = "aoc_macros"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true
doctest = false

[dependencies]
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn ={ version = "2.0.110", features = ["full", "extra-traits"] } 
